apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: monitoring
  labels:
    app: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
  template:
    metadata:
      labels:
        app: zabbix
    spec:
      containers:
        - name: zabbix
          image: zabbix/zabbix-server-pgsql:alpine-latest
          ports:
            - containerPort: 10051
          env:
            - name: DB_SERVER_HOST
              value: zabbix-postgres
            - name: DB_SERVER_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: POSTGRES_PASSWORD
            - name: ZBX_SERVER_NAME
              value: Zabbix on Kubernetes
            - name: ZBX_ENABLE_SNMP_TRAPS
              value: "false"
