apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  labels:
    app: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_SERVER_HOST
              value: zabbix-postgres
            - name: DB_SERVER_PORT
              value: "5432"
            - name: DB_SERVER_DBNAME
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: POSTGRES_DB
            - name: DB_SERVER_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: POSTGRES_USER
            - name: DB_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: POSTGRES_PASSWORD
            - name: ZBX_SERVER_HOST
              value: zabbix-service
            - name: ZBX_SERVER_PORT
              value: "10051"
            - name: PHP_TZ
              value: Europe/Moscow
