apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-node-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-node-test
  template:
    metadata:
      labels:
        app: argo-node-test
    spec:
      containers:
        - name: node
          image: edgarnj/argo-node-test:1.1
          ports:
            - containerPort: 3000