apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: kiali-system
  labels:
    app: kiali
spec:
  selector:
    app: kiali
  ports:
    - name: http
      port: 20001
      targetPort: 20001
