apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: zabbix-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-zabbix
        protocol: HTTP
      hosts:
        - zabbix.example.com
